name: challenge-app-fe DevCI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: challenge-app-fe DevCI
    runs-on: ubuntu-latest
    env:
      APPLICATION: challenge-app
      ROLE: fe
      REGION: ap-southeast-2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12

    - name: apt-get update
      run: sudo apt-get update

    - name: install aws cli
      run: sudo apt-get install awscli

    - name: Install TS
      run: npm install typescript

    - name: Install CDK
      run: npm install -g aws-cdk@1.100.0

    - name: Verify Cache
      run: npm cache verify

    - name: Install packages
      run: npm install

    - name: Configure AWS Credentials for Dev account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Set env
      run: echo "AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

    - name: Deploy CDK
      run: cdk deploy -c account=${AWS_ACCOUNT} -c region=${REGION} -c branch=${GITHUB_REF##*/} -c application=${APPLICATION} -c role=${ROLE} --require-approval never
